var namespacefs =
[
    [ "meeting", "namespacefs_1_1meeting.html", "namespacefs_1_1meeting" ],
    [ "ActiveSpeakerNotifications", "classfs_1_1_active_speaker_notifications.html", "classfs_1_1_active_speaker_notifications" ],
    [ "ActiveSpeakerNotificationsNullDelegate", "classfs_1_1_active_speaker_notifications_null_delegate.html", "classfs_1_1_active_speaker_notifications_null_delegate" ],
    [ "AttendeeDecorator", "classfs_1_1_attendee_decorator.html", "classfs_1_1_attendee_decorator" ],
    [ "AttendeeNotifications", "classfs_1_1_attendee_notifications.html", "classfs_1_1_attendee_notifications" ],
    [ "AttendeeNotificationsNullDelegate", "classfs_1_1_attendee_notifications_null_delegate.html", "classfs_1_1_attendee_notifications_null_delegate" ],
    [ "AttendeesController", "classfs_1_1_attendees_controller.html", "classfs_1_1_attendees_controller" ],
    [ "AttendeesManager", "classfs_1_1_attendees_manager.html", "classfs_1_1_attendees_manager" ],
    [ "BasicHandler", "classfs_1_1_basic_handler.html", "classfs_1_1_basic_handler" ],
    [ "BridgeDetails", "namespacefs.html#structfs_1_1_bridge_details", "namespacefs_structfs_1_1_bridge_details_dup" ],
    [ "BroadcasterNotifications", "classfs_1_1_broadcaster_notifications.html", "classfs_1_1_broadcaster_notifications" ],
    [ "BroadcasterPresentationNotifications", "classfs_1_1_broadcaster_presentation_notifications.html", "classfs_1_1_broadcaster_presentation_notifications" ],
    [ "BroadcasterPresentationNotificationsNullDelegate", "classfs_1_1_broadcaster_presentation_notifications_null_delegate.html", "classfs_1_1_broadcaster_presentation_notifications_null_delegate" ],
    [ "BroadcasterRecordingNotifications", "classfs_1_1_broadcaster_recording_notifications.html", "classfs_1_1_broadcaster_recording_notifications" ],
    [ "BroadcasterRecordingNotificationsNullDelegate", "classfs_1_1_broadcaster_recording_notifications_null_delegate.html", "classfs_1_1_broadcaster_recording_notifications_null_delegate" ],
    [ "Buffer", "classfs_1_1_buffer.html", "classfs_1_1_buffer" ],
    [ "BundledAttendee", "classfs_1_1_bundled_attendee.html", "classfs_1_1_bundled_attendee" ],
    [ "BundledAttendeeNotificationsNullDelegate", "classfs_1_1_bundled_attendee_notifications_null_delegate.html", "classfs_1_1_bundled_attendee_notifications_null_delegate" ],
    [ "BundleNotifications", "classfs_1_1_bundle_notifications.html", "classfs_1_1_bundle_notifications" ],
    [ "ChatController", "classfs_1_1_chat_controller.html", "classfs_1_1_chat_controller" ],
    [ "ChatNotifications", "classfs_1_1_chat_notifications.html", "classfs_1_1_chat_notifications" ],
    [ "ChatNotificationsNullDelegate", "classfs_1_1_chat_notifications_null_delegate.html", "classfs_1_1_chat_notifications_null_delegate" ],
    [ "ConferenceDescriptor", "classfs_1_1_conference_descriptor.html", "classfs_1_1_conference_descriptor" ],
    [ "ConferenceState", "structfs_1_1_conference_state.html", "structfs_1_1_conference_state" ],
    [ "CountryCallingCode", "structfs_1_1_country_calling_code.html", "structfs_1_1_country_calling_code" ],
    [ "DelegatesProvider", "classfs_1_1_delegates_provider.html", "classfs_1_1_delegates_provider" ],
    [ "FSCapabilitiesPkt", "classfs_1_1_f_s_capabilities_pkt.html", "classfs_1_1_f_s_capabilities_pkt" ],
    [ "FSCompoundMsgPkt", "classfs_1_1_f_s_compound_msg_pkt.html", "classfs_1_1_f_s_compound_msg_pkt" ],
    [ "FSDirectorClipboardContentPkt", "classfs_1_1_f_s_director_clipboard_content_pkt.html", "classfs_1_1_f_s_director_clipboard_content_pkt" ],
    [ "FSDirectorKeyboardEventPkt", "classfs_1_1_f_s_director_keyboard_event_pkt.html", "classfs_1_1_f_s_director_keyboard_event_pkt" ],
    [ "FSDirectorMouseEventPkt", "classfs_1_1_f_s_director_mouse_event_pkt.html", "classfs_1_1_f_s_director_mouse_event_pkt" ],
    [ "FSDirectorPromotePkt", "classfs_1_1_f_s_director_promote_pkt.html", "classfs_1_1_f_s_director_promote_pkt" ],
    [ "FSDirectorPromoteStatusPkt", "classfs_1_1_f_s_director_promote_status_pkt.html", "classfs_1_1_f_s_director_promote_status_pkt" ],
    [ "FSDirectorRequestPkt", "classfs_1_1_f_s_director_request_pkt.html", "classfs_1_1_f_s_director_request_pkt" ],
    [ "FSDirectorScrollWheelEventPkt", "classfs_1_1_f_s_director_scroll_wheel_event_pkt.html", "classfs_1_1_f_s_director_scroll_wheel_event_pkt" ],
    [ "FSDropPkt", "classfs_1_1_f_s_drop_pkt.html", "classfs_1_1_f_s_drop_pkt" ],
    [ "FSEndOfFramePkt", "classfs_1_1_f_s_end_of_frame_pkt.html", "classfs_1_1_f_s_end_of_frame_pkt" ],
    [ "FSInfoBlockPkt", "classfs_1_1_f_s_info_block_pkt.html", "classfs_1_1_f_s_info_block_pkt" ],
    [ "FSPacket", "classfs_1_1_f_s_packet.html", "classfs_1_1_f_s_packet" ],
    [ "FSParticipantClickPkt", "classfs_1_1_f_s_participant_click_pkt.html", "classfs_1_1_f_s_participant_click_pkt" ],
    [ "FSPktArrayEntry", "classfs_1_1_f_s_pkt_array_entry.html", "classfs_1_1_f_s_pkt_array_entry" ],
    [ "FSPktEntry", "classfs_1_1_f_s_pkt_entry.html", "classfs_1_1_f_s_pkt_entry" ],
    [ "FSPktStream", "classfs_1_1_f_s_pkt_stream.html", "classfs_1_1_f_s_pkt_stream" ],
    [ "FSPresenterCursorPkt", "classfs_1_1_f_s_presenter_cursor_pkt.html", "classfs_1_1_f_s_presenter_cursor_pkt" ],
    [ "FSPresenterReleaseControlPkt", "classfs_1_1_f_s_presenter_release_control_pkt.html", "classfs_1_1_f_s_presenter_release_control_pkt" ],
    [ "FSPresenterTakeControlPkt", "classfs_1_1_f_s_presenter_take_control_pkt.html", "classfs_1_1_f_s_presenter_take_control_pkt" ],
    [ "FSReconnectCtrlPkt", "classfs_1_1_f_s_reconnect_ctrl_pkt.html", "classfs_1_1_f_s_reconnect_ctrl_pkt" ],
    [ "FSScreenBlocksPkt", "classfs_1_1_f_s_screen_blocks_pkt.html", "classfs_1_1_f_s_screen_blocks_pkt" ],
    [ "FSSessionStatusPkt", "classfs_1_1_f_s_session_status_pkt.html", "classfs_1_1_f_s_session_status_pkt" ],
    [ "GroupDescriptor", "classfs_1_1_group_descriptor.html", "classfs_1_1_group_descriptor" ],
    [ "GroupState", "structfs_1_1_group_state.html", "structfs_1_1_group_state" ],
    [ "IActiveSpeakerNotificationsDelegate", "classfs_1_1_i_active_speaker_notifications_delegate.html", "classfs_1_1_i_active_speaker_notifications_delegate" ],
    [ "IAttendeeContainer", "classfs_1_1_i_attendee_container.html", "classfs_1_1_i_attendee_container" ],
    [ "IAttendeeNotificationsDelegate", "classfs_1_1_i_attendee_notifications_delegate.html", "classfs_1_1_i_attendee_notifications_delegate" ],
    [ "IBroadcasterPresentationNotificationsDelegate", "classfs_1_1_i_broadcaster_presentation_notifications_delegate.html", "classfs_1_1_i_broadcaster_presentation_notifications_delegate" ],
    [ "IBroadcasterRecordingNotificationsDelegate", "classfs_1_1_i_broadcaster_recording_notifications_delegate.html", "classfs_1_1_i_broadcaster_recording_notifications_delegate" ],
    [ "IBundledAttendeeNotificationsDelegate", "classfs_1_1_i_bundled_attendee_notifications_delegate.html", "classfs_1_1_i_bundled_attendee_notifications_delegate" ],
    [ "IChatNotificationsDelegate", "classfs_1_1_i_chat_notifications_delegate.html", "classfs_1_1_i_chat_notifications_delegate" ],
    [ "IDelegatesConfiguration", "classfs_1_1_i_delegates_configuration.html", null ],
    [ "IDelegatesGetter", "classfs_1_1_i_delegates_getter.html", "classfs_1_1_i_delegates_getter" ],
    [ "IDelegatesSetter", "classfs_1_1_i_delegates_setter.html", "classfs_1_1_i_delegates_setter" ],
    [ "IMeetingAttendeePrivate", "classfs_1_1_i_meeting_attendee_private.html", "classfs_1_1_i_meeting_attendee_private" ],
    [ "INetworkInspectorNotificationsDelegate", "classfs_1_1_i_network_inspector_notifications_delegate.html", "classfs_1_1_i_network_inspector_notifications_delegate" ],
    [ "InvalidExecutionTheadException", "classfs_1_1_invalid_execution_thead_exception.html", "classfs_1_1_invalid_execution_thead_exception" ],
    [ "IOServiceController", "classfs_1_1_i_o_service_controller.html", "classfs_1_1_i_o_service_controller" ],
    [ "IOServiceProvider", "structfs_1_1_i_o_service_provider.html", "structfs_1_1_i_o_service_provider" ],
    [ "IRawRTMessageNotificationsDelegate", "classfs_1_1_i_raw_r_t_message_notifications_delegate.html", "classfs_1_1_i_raw_r_t_message_notifications_delegate" ],
    [ "IScreenSharingNotificationsDelegate", "classfs_1_1_i_screen_sharing_notifications_delegate.html", "classfs_1_1_i_screen_sharing_notifications_delegate" ],
    [ "ISessionNotificationsDelegate", "classfs_1_1_i_session_notifications_delegate.html", "classfs_1_1_i_session_notifications_delegate" ],
    [ "IVideoNotificationsDelegate", "classfs_1_1_i_video_notifications_delegate.html", "classfs_1_1_i_video_notifications_delegate" ],
    [ "IVoIPNotificationsDelegate", "classfs_1_1_i_vo_i_p_notifications_delegate.html", "classfs_1_1_i_vo_i_p_notifications_delegate" ],
    [ "MeetingAttendee", "classfs_1_1_meeting_attendee.html", "classfs_1_1_meeting_attendee" ],
    [ "MeetingAttendeeBase", "classfs_1_1_meeting_attendee_base.html", "classfs_1_1_meeting_attendee_base" ],
    [ "MeetingAttendeePublic", "classfs_1_1_meeting_attendee_public.html", "classfs_1_1_meeting_attendee_public" ],
    [ "MeetingAttendeeReadonly", "classfs_1_1_meeting_attendee_readonly.html", "classfs_1_1_meeting_attendee_readonly" ],
    [ "MeetingClient", "classfs_1_1_meeting_client.html", "classfs_1_1_meeting_client" ],
    [ "MeetingClientSession", "classfs_1_1_meeting_client_session.html", "classfs_1_1_meeting_client_session" ],
    [ "MeetingControllerBase", "classfs_1_1_meeting_controller_base.html", "classfs_1_1_meeting_controller_base" ],
    [ "MeetingLobby", "classfs_1_1_meeting_lobby.html", "classfs_1_1_meeting_lobby" ],
    [ "MeetingLobbyProxy", "classfs_1_1_meeting_lobby_proxy.html", "classfs_1_1_meeting_lobby_proxy" ],
    [ "MeetingSessionParameters", "structfs_1_1_meeting_session_parameters.html", "structfs_1_1_meeting_session_parameters" ],
    [ "ModuleVersion", "classfs_1_1_module_version.html", "classfs_1_1_module_version" ],
    [ "NetworkIdentifier", "classfs_1_1_network_identifier.html", "classfs_1_1_network_identifier" ],
    [ "NetworkInspectorClient", "classfs_1_1_network_inspector_client.html", "classfs_1_1_network_inspector_client" ],
    [ "NetworkInspectorController", "classfs_1_1_network_inspector_controller.html", "classfs_1_1_network_inspector_controller" ],
    [ "NotificationHandler", "classfs_1_1_notification_handler.html", "classfs_1_1_notification_handler" ],
    [ "null_impl", "structfs_1_1null__impl.html", null ],
    [ "null_impl< IActiveSpeakerNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_active_speaker_notifications_delegate_01_4.html", null ],
    [ "null_impl< IAttendeeNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_attendee_notifications_delegate_01_4.html", null ],
    [ "null_impl< IBroadcasterPresentationNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_broadcaster_presentation_notifications_delegate_01_4.html", null ],
    [ "null_impl< IBroadcasterRecordingNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_broadcaster_recording_notifications_delegate_01_4.html", null ],
    [ "null_impl< IBundledAttendeeNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_bundled_attendee_notifications_delegate_01_4.html", null ],
    [ "null_impl< IChatNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_chat_notifications_delegate_01_4.html", null ],
    [ "null_impl< IRawRTMessageNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_raw_r_t_message_notifications_delegate_01_4.html", null ],
    [ "null_impl< IScreenSharingNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_screen_sharing_notifications_delegate_01_4.html", null ],
    [ "null_impl< ISessionNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_session_notifications_delegate_01_4.html", null ],
    [ "null_impl< IVideoNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_video_notifications_delegate_01_4.html", null ],
    [ "null_impl< IVoIPNotificationsDelegate >", "structfs_1_1null__impl_3_01_i_vo_i_p_notifications_delegate_01_4.html", null ],
    [ "PhoneNumberUtils", "classfs_1_1_phone_number_utils.html", "classfs_1_1_phone_number_utils" ],
    [ "PresentationBroadcastController", "classfs_1_1_presentation_broadcast_controller.html", "classfs_1_1_presentation_broadcast_controller" ],
    [ "RawRTMessageNotifications", "classfs_1_1_raw_r_t_message_notifications.html", "classfs_1_1_raw_r_t_message_notifications" ],
    [ "RawRTMessageNotificationsNullDelegate", "classfs_1_1_raw_r_t_message_notifications_null_delegate.html", "classfs_1_1_raw_r_t_message_notifications_null_delegate" ],
    [ "RawRTMessagesController", "classfs_1_1_raw_r_t_messages_controller.html", "classfs_1_1_raw_r_t_messages_controller" ],
    [ "RecordingBroadcastController", "classfs_1_1_recording_broadcast_controller.html", "classfs_1_1_recording_broadcast_controller" ],
    [ "RTNotificationsController", "classfs_1_1_r_t_notifications_controller.html", "classfs_1_1_r_t_notifications_controller" ],
    [ "RTPresentationBroadcastHandler", "classfs_1_1_r_t_presentation_broadcast_handler.html", "classfs_1_1_r_t_presentation_broadcast_handler" ],
    [ "RTRecordingBroadcastHandler", "classfs_1_1_r_t_recording_broadcast_handler.html", "classfs_1_1_r_t_recording_broadcast_handler" ],
    [ "ScreenSharingController", "classfs_1_1_screen_sharing_controller.html", "classfs_1_1_screen_sharing_controller" ],
    [ "ScreenSharingNotifications", "classfs_1_1_screen_sharing_notifications.html", "classfs_1_1_screen_sharing_notifications" ],
    [ "ScreenSharingNotificationsNullDelegate", "classfs_1_1_screen_sharing_notifications_null_delegate.html", "classfs_1_1_screen_sharing_notifications_null_delegate" ],
    [ "SessionNotifications", "classfs_1_1_session_notifications.html", "classfs_1_1_session_notifications" ],
    [ "SessionNotificationsNullDelegate", "classfs_1_1_session_notifications_null_delegate.html", "classfs_1_1_session_notifications_null_delegate" ],
    [ "ThreadDescriptor", "classfs_1_1_thread_descriptor.html", "classfs_1_1_thread_descriptor" ],
    [ "TSingleton", "classfs_1_1_t_singleton.html", "classfs_1_1_t_singleton" ],
    [ "VideoController", "classfs_1_1_video_controller.html", "classfs_1_1_video_controller" ],
    [ "VideoEngineProxy", "classfs_1_1_video_engine_proxy.html", "classfs_1_1_video_engine_proxy" ],
    [ "VideoNotifications", "classfs_1_1_video_notifications.html", "classfs_1_1_video_notifications" ],
    [ "VideoNotificationsNullDelegate", "classfs_1_1_video_notifications_null_delegate.html", "classfs_1_1_video_notifications_null_delegate" ],
    [ "VideoRenderer", "classfs_1_1_video_renderer.html", "classfs_1_1_video_renderer" ],
    [ "VoiceEngineProxy", "classfs_1_1_voice_engine_proxy.html", "classfs_1_1_voice_engine_proxy" ],
    [ "VoIPClientDelegate", "classfs_1_1_vo_i_p_client_delegate.html", "classfs_1_1_vo_i_p_client_delegate" ],
    [ "VoIPClientProxy", "classfs_1_1_vo_i_p_client_proxy.html", "classfs_1_1_vo_i_p_client_proxy" ],
    [ "VoIPController", "classfs_1_1_vo_i_p_controller.html", "classfs_1_1_vo_i_p_controller" ],
    [ "VoIPNotifications", "classfs_1_1_vo_i_p_notifications.html", "classfs_1_1_vo_i_p_notifications" ],
    [ "VoIPNotificationsNullDelegate", "classfs_1_1_vo_i_p_notifications_null_delegate.html", "classfs_1_1_vo_i_p_notifications_null_delegate" ],
    [ "Wrapper", "classfs_1_1_wrapper.html", "classfs_1_1_wrapper" ]
];